sudo : required

services: 
  -docker

before_install:
  - docker build -t bibekthapahere/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bibekthapahere/react-test npm test
  
after_success:
    - docker build -t bibekthapahere/multi-client ./client
    - docker build -t bibekthapahere/multi-nginx ./nginx
    - docker build -t bibekthapahere/multi-worker ./worker
    - docker build -t bibekthapahere/multi-server ./server
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push bibekthapahere/multi-client
    - docker push bibekthapahere/multi-nginx
    - docker push bibekthapahere/multi-worker
    - docker push bibekthapahere/multi-server



  


